app/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^fitnesse/', include('fitnesse.urls', namespace="fitnesse")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^gitlab/', include('gitlab.urls', namespace="gitlab")),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/app/favicon.ico')),
)

fitnesse/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import RedirectView

from fitnesse import views
from fitnesse import forms
from fitnesse import tasks

urlpatterns = patterns('',
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/app/favicon.ico')),
    url(r'^$', views.jobs, name='jobs'),
    url(r'^import_job/(?P<job_name>\S+)/$', tasks.import_job, name='import_job'),
    url(r'^changelog/$', views.changelog, name='changelog'),
    url(r'^settings_show/$', forms.common_settings_show, name='common_settings_show'),
    url(r'^settings_save/$', forms.common_settings_save, name='common_settings_save'),
    url(r'^(?P<job_id>\d+)/$', views.results_aggregation, name='results_aggregation'),    
    url(r'^(?P<job_id>\d+)/settings_show/$', forms.job_settings_show, name='job_settings_show'),
    url(r'^(?P<job_id>\d+)/settings_save/$', forms.job_settings_save, name='job_settings_save'),
    url(r'^(?P<job_id>\d+)/charts/$', views.job_charts, name='job_charts'),
    url(r'^(?P<job_id>\d+)/r/(?P<test_id>\d+)/$', views.test_result, name='test_result'),
    url(r'^(?P<job_id>\d+)/r/(?P<test_id>\d+)/fitnesse_result$', views.fitnesse_result, name='fitnesse_result'),
)

fitnesse/models.py
from django.db import models


class CommonSettings(models.Model):
    name = models.CharField(max_length=500, unique=True)
    number = models.IntegerField(null=True, default=None)
    text = models.CharField(max_length=500, null=True, default=None)

    def __str__(self):
        return "%s" % self.name


class Job(models.Model):
    name = models.CharField(max_length=500, unique=True)

    def __str__(self):
        return "%s" % self.name


class JobSettings(models.Model):
    job_ptr = models.ForeignKey(Job)
    name = models.CharField(max_length=500)
    number = models.IntegerField(null=True, default=None)
    text = models.CharField(max_length=500, null=True, default=None)

    class Meta:
        unique_together = (("job_ptr", "name"),)

    def __str__(self):
        return "%s: %s" % (self.job_ptr.name, self.name)


class Build(models.Model):
    job_ptr = models.ForeignKey(Job)
    number = models.IntegerField(default=-1)
    is_load = models.BooleanField(default=False)
    error_description = models.TextField(null=True, default=None)
    is_success = models.BooleanField(default=False)
    start_time = models.DateTimeField(null=True, default=None)

    class Meta:
        unique_together = (("job_ptr", "number"),)

    def __str__(self):
        if self.is_load:
            return "%s (%i)" % (self.job_ptr.name, self.number)
        else:
            return "%s (%i): error: %s" % (self.job_ptr.name, self.number, self.error_description)


class KeyBuildArtifact(models.Model):
    key = models.CharField(null=False, max_length=100)
    subkey = models.CharField(null=False, max_length=100)

    class Meta:
        unique_together = (("key", "subkey"),)

    def __str__(self):
        return "%s.%s" % (self.key, self.subkey)


class BuildArtifact(models.Model):
    build_ptr = models.ForeignKey(Build)
    key_ptr = models.ForeignKey(KeyBuildArtifact)
    content = models.BinaryField(default=None)

    class Meta:
        unique_together = (("build_ptr", "key_ptr"),)

    def __str__(self):
        job_name = self.build_ptr.job_ptr.name
        build_number = self.build_ptr.number
        return "%s (%i): %s" % (job_name, build_number, unicode(self.key_ptr))


class Suite(models.Model):
    build_ptr = models.ForeignKey(Build)
    name = models.CharField(max_length=500)
    run_durations = models.IntegerField(default=0)
    is_load = models.BooleanField(default=False)
    error_description = models.TextField(null=True, default=None)
    is_success = models.BooleanField(default=False)

    class Meta:
        unique_together = (("build_ptr", "name"),)

    def __str__(self):
        job_name = self.build_ptr.job_ptr.name
        build_number = self.build_ptr.number
        if self.is_load:
            return "%s (%i): %s" % (job_name, build_number, self.name)
        else:
            return "%s (%i): %s: error: %s" % (job_name, build_number, self.name, self.error_description)


class Test(models.Model):
    suite_ptr = models.ForeignKey(Suite)
    number = models.IntegerField(default=0)
    name = models.CharField(max_length=500)
    run_durations = models.IntegerField(default=0)
    is_success = models.BooleanField(default=False)

    class Meta:
        unique_together = (("suite_ptr", "name"),)

    def __str__(self):
        job_name = self.suite_ptr.build_ptr.job_ptr.name
        build_number = self.suite_ptr.build_ptr.number
        return "%s (%i): %i. %s.%s" % (job_name, build_number, self.number, self.suite_ptr.name, self.name)


class KeyTestArtifact(models.Model):
    key = models.CharField(null=False, max_length=100, unique=True)

    def __str__(self):
        return self.key


class TestArtifact(models.Model):
    test_ptr = models.ForeignKey(Test)
    key_ptr = models.ForeignKey(KeyTestArtifact)
    content = models.BinaryField(default=None)

    class Meta:
        unique_together = (("test_ptr", "key_ptr"),)

    def __str__(self):
        return "%s.%s: %s" % (self.test_ptr.suite_ptr.name, self.test_ptr.name, self.key_ptr.key)

fitnesse/forms.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from fitnesse.models import Job

import fitnesse.helper.settings as settings


def common_settings_show(request):
    return render(request, 'fitnesse/common_settings.html', {'JenkinsUrl': settings.get_jenkins_url()})

def common_settings_save(request):
    settings.set_jenkins_url(request.POST['JenkinsUrl'])
    return HttpResponseRedirect(reverse('fitnesse:jobs'))

def job_settings_show(request, job_id):
    job = get_object_or_404(Job, pk = job_id)
    return render(request, 'fitnesse/job_settings.html', {'Job': job, 'MaxBuilds': settings.get_max_buids(job)})

def job_settings_save(request, job_id):
    job = get_object_or_404(Job, pk = job_id)
    settings.set_max_buids(job, request.POST['MaxBuilds'])
    return HttpResponseRedirect(reverse('fitnesse:jobs'))

fitnesse/views.py
# -*- coding: utf-8 -*-

from django.db.models import Max, Q
from aggregate_if import Count
from django.utils.html import escape
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from fitnesse.models import Job, Build, KeyBuildArtifact, BuildArtifact, Suite, Test, KeyTestArtifact, TestArtifact
import fitnesse.helper.settings as settings

import re
import json
import time
import pytz
import collections


def changelog(request):
    return render(request, 'fitnesse/changelog.html')


def jobs(request):
    jobs = Job.objects.all().annotate(build_count=Count('build'), build_last=Max('build__number'), start_time=Max('build__number'), _stat=Max('build__number')).order_by('name')
    last_jobs = [job.build_last for job in jobs]        
    builds_results = Test.objects.filter(suite_ptr__build_ptr__number__in = last_jobs).values('suite_ptr__build_ptr__job_ptr__id', 'suite_ptr__build_ptr__start_time').annotate(dummy=Count('suite_ptr__build_ptr__id'), total = Count('id'), count_succeess = Count('is_success', only=Q(is_success=True))).order_by('suite_ptr__build_ptr__number')    
    local_tz = pytz.timezone('Europe/Moscow')
    result_map = {it['suite_ptr__build_ptr__job_ptr__id']:
                      {'last_build_stat': '%i of %i failed' % (it['total'] - it['count_succeess'], it['total']),
                       'start_time': local_tz.normalize(it['suite_ptr__build_ptr__start_time'].astimezone(local_tz)).strftime('%H:%M %d/%m/%y') if it['suite_ptr__build_ptr__start_time'] is not None else None}
                            for it in builds_results}

    for job in jobs:
        job.last_build_stat = result_map[job.id]['last_build_stat'] if job.id in result_map else '-'
        job.build_last = '-' if job.build_last is None else '#' + str(job.build_last)
        job.start_time = result_map[job.id]['start_time'] if job.id in result_map and result_map[job.id]['start_time'] is not None else '-'

    return render(request, 'fitnesse/jobs.html', {'jobs': jobs})

def job_charts(request, job_id):
    job = get_object_or_404(Job, pk = job_id)
    query = Test.objects.filter(suite_ptr__build_ptr__job_ptr = job).values('suite_ptr__build_ptr__number').annotate(dummy=Count('suite_ptr__build_ptr__id'), total = Count('id'), count_succeess = Count('is_success', only=Q(is_success=True))).order_by('suite_ptr__build_ptr__number')
    
    separators = (',', ':')
    builds = json.dumps(['#' + str(it['suite_ptr__build_ptr__number']) for it in query], separators=separators)
    succeess = json.dumps([it['count_succeess'] for it in query], separators=separators)
    error = json.dumps([it['total'] - it['count_succeess'] for it in query], separators=separators)

    return render(request, 'fitnesse/job_charts.html', {'Job': job, 'Builds': builds, 'Succeess': succeess, 'Error': error})

def _get_tests_by_job(job):
    all_tests = Test.objects.filter(suite_ptr__build_ptr__job_ptr = job).values('id', 'name', 'is_success', 'suite_ptr__name', 'suite_ptr__build_ptr__number').order_by('suite_ptr__name', 'number', '-suite_ptr__build_ptr__number')
    for it in all_tests:
        yield it['id'], it['is_success'], it['name'], it['suite_ptr__name'], it['suite_ptr__build_ptr__number']
    yield None, None, None, None, None

def results_aggregation(request, job_id):
    t_begin = time.time()

    separators = (',', ':')
    job = get_object_or_404(Job, pk = job_id)

    builds = Build.objects.filter(job_ptr = job).order_by('-number')
    if not builds:
        return render(request, 'fitnesse/not_load.html', {'job': job})
    build_count = builds.count()
    build_map = {build.number: num for (num, build) in enumerate(builds)}
    build_list = json.dumps([it.number for it in builds], separators=separators)

    tests = {}
    generator = iter(_get_tests_by_job(job))
    test_id, test_success, old_test_name, old_suite_name, build_number = next(generator)
    test_result = [[0, 0]]*build_count
    test_result[build_map[build_number]] = [test_id, 1 if test_success else 0]
    suite_result = collections.OrderedDict()
    
    for test_id, test_success, test_name, suite_name, build_number in generator:
        if test_name != old_test_name:
            suite_result[old_test_name] = test_result
            old_test_name = test_name
            if suite_name == old_suite_name and test_name in suite_result.keys():
                test_result = suite_result[test_name]
            else:
                test_result = [[0, 0]]*build_count

        if suite_name != old_suite_name:
            tests[old_suite_name] = suite_result
            old_suite_name = suite_name
            suite_result = collections.OrderedDict()

        if test_id is not None:
            test_result[build_map[build_number]] = [test_id, 1 if test_success else 0]    

    url_base = '"' + settings.get_jenkins_url() + '/job/' + job.name + '/"'
    r =  render(request, 'fitnesse/results_aggregation.html', {'job': job, 'builds': build_list, 'build_count': build_count,'tests': json.dumps(tests, separators=separators), 'url_base': url_base})
    return r

def find_suite_log(artifact, suite_name, test_name):
    start_pattern = '!!! (\d|\.|\:|\ )+start test: \".*\.%s.%s\" !!!' % (suite_name, test_name)
    stop_pattern = '!!! (\d|\.|\:|\ )+stop test: \".*\.%s.%s\" !!!.*\s' % (suite_name, test_name)

    if not artifact:
        return {'before': '', 'test': 'not found fitnesse logs on client artifacts', 'after': ''}

    text = bytes(artifact[0].content).decode('866')
    m_start = re.search(start_pattern, text)
    m_stop = re.search(stop_pattern, text)
    if (not m_start) or (not m_stop):
        return {'before': '', 'test': 'not found pattern ({0}) or ({1}) in client fitnesse log'.format(start_pattern, stop_pattern), 'after': ''}

    before_text = '\r'.join(text[:m_start.start()].split('\r')[-20:])
    find_text = text[m_start.start():m_stop.end()].rstrip()
    after_text = '\r'.join(text[m_stop.end():].split('\r')[:20])

    def show_error(text, error_str):
        return text.replace(error_str, '<div class="fitnesse-error">' + error_str + '</div>')        

    result = []
    for it in [before_text, find_text, after_text]:
        it = escape(it).replace('\r\n', '<br/>').replace('\r', '<br/>').replace('\n', '<br/>')
        it = show_error(show_error(show_error(it, 'RPC_E_CALL_CANCELED'), 'System.Management.IWbemServices'), u'Узел назначения недоступен')
        result.append(it)

    return {'before': result[0], 'test': result[1], 'after': result[2]}

def test_result(request, job_id, test_id):
    job = get_object_or_404(Job, pk = job_id)
    test_info = Test.objects.filter(pk = test_id).values('name', 'suite_ptr__name', 'suite_ptr__build_ptr', 'suite_ptr__build_ptr__number')
    if not test_info:
        raise Http404

    build_id = test_info[0]['suite_ptr__build_ptr']
    build_number = str(test_info[0]['suite_ptr__build_ptr__number'])
    suite_name = str(test_info[0]['suite_ptr__name'])
    test_name = str(test_info[0]['name'])

    artifact_key = get_object_or_404(KeyBuildArtifact, key = "ClientW8", subkey = "fitnesse_log")
    artifact = BuildArtifact.objects.filter(build_ptr = build_id, key_ptr = artifact_key)
    fitnesse_result = find_suite_log(artifact, suite_name, test_name)

    test_full_name = '%s.%s' % (suite_name, test_name)
    build_url = settings.get_jenkins_url() + '/job/' + job.name + '/' + build_number
    return render(request, 'fitnesse/test_result.html', {'job': job, 'test_id': test_id, 'build_id': build_number, 'build_url': build_url, 'test_name': test_full_name, 'fitnesse_result': fitnesse_result})


def fitnesse_result(request, job_id, test_id):
    job = get_object_or_404(Job, pk=job_id)
    artifact_key = get_object_or_404(KeyTestArtifact, key="fitnesse_result")
    artifact = get_object_or_404(TestArtifact, test_ptr=test_id, key_ptr=artifact_key)
    artifact.content = bytes(artifact.content)

    return render(request, 'fitnesse/fitnesse_result.html', {'job': job, 'artifact': artifact})

fitnesse/templates/fitnesse/_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{% block title %}Title{% endblock %}</title>
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet" />
  <link href="{% static 'fitnesse/project/css/fitnesse.css' %}" type="text/css" rel="stylesheet" />
  <link href="{% static 'app/favicon.ico' %}" rel="shortcut icon" />
</head>
<body>
{% block body %}{% endblock %}
<script src="{% static 'jquery/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'django_ajax/jquery.ajax.min.js' %}" type="text/javascript"></script>
{% block script %}{% endblock %}
</body>
</html>

fitnesse/templates/fitnesse/changelog.html
{% extends "fitnesse/_base.html" %}
{% load staticfiles %}
{% block title %}Changelog{% endblock %}
{% block body %}
<ul class="fit_breadcrumb">
  <li><a href="/fitnesse/">Home</a><span class="divider">/</span></li>
  <li class="active">Changelog</li>
</ul>
<div class="container">
  <div class="page-header">
    <h1>Changelog</h1>
  </div>
  <div>
    <p>Version 0.5</p>
    <ul>
      <li>Самостоятельная генерация таблицы результатов, без вспомогательных библиотек</li>
      <li>Переход на python3</li>
    </ul>
    <p>Version 0.4</p>
    <ul>
      <li>Поддержка дублирующихся названия тестов</li>
      <li>Отображение build id в результатах тестов</li>
      <li>Раскрытие include страниц значками "+"/"-"</li>
      <li>Поддержка fitnesse v20150814</li>
      <li>Работа с докер</li>
      <li>Обработка хуков от GitLab</li>
      <li>Поддержка fitnesse v20140630</li>
    </ul>
    <p>Version 0.3</p>
    <ul>
      <li>Вывод времени последнего билда</li>
      <li>Добавил favicon, breadcrumb</li>
      <li>Страница с результатами теперь реагирует на Page Up\Down</li>
      <li>Ссылки на билд в jenkins</li>
      <li>Добавил вывод информации о последнем билде</li>
    </ul>
    <p>Version 0.2</p>
    <ul>
      <li>Графики для каждой задачи с кол-вом успешных и ошибочных тестов</li>
      <li>Добавлены настройки: jenkins url и кол-во хранящихся билдов</li>
      <li>Добавил отступ для названий тестов в таблице результатов</li>
    </ul>
    <p>Version 0.1</p>
    <ul>
      <li>Появление на свет сего замечательного продукта</li>
    </ul>
  </div>
</div>
{% endblock %}

fitnesse/templates/fitnesse/common_settings.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Общие настройки</title>
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'app/favicon.ico' %}" />
</head>
<body>
  <form action="{% url 'fitnesse:common_settings_save' %}" method="post" role="form">
    {% csrf_token %}
    <div class="container">
      <div class="page-header">
        <h1>Общие настройки</h1>
      </div>
      <div class="form-group">
        <label for="JenkinsUrl-id">Jenkins url</label>
        <input class="form-control" type="url" name="JenkinsUrl" id="JenkinsUrl-id" value="{{ JenkinsUrl }}" placeholder="http://0.0.0.0:8080/">
      </div>
      <button type="submit" class="btn btn-default">Сохранить</button>
    </div>
  </form>
  <script src="{% static 'jquery/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

fitnesse/templates/fitnesse/fitnesse_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Результаты fitnesse тестов</title>
  <link rel="stylesheet" type="text/css" href="{% static 'fitnesse/fitnesse/css/fitnesse_wiki.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'fitnesse/fitnesse/css/fitnesse_pages.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'fitnesse/fitnesse/css/fitnesse-bootstrap.css' %}" />
  <style>
   .testPage {
      padding-top: 10px;
    }
  </style>
  <link rel="shortcut icon" href="{% static 'app/favicon.ico' %}" />
</head>
<body class="testPage">
  <article id="article">
    {% autoescape off %}
    {{artifact.content}}
    {% endautoescape %}
  </article>

  <script src="{% static 'fitnesse/fitnesse/javascript/jquery-1.7.2.min.js' %}" type="text/javascript" ></script>
  <script src="{% static 'fitnesse/fitnesse/javascript/fitnesse.js' %}" type="text/javascript"></script>
<script type="text/javascript">
  function resize() { $('#frame_fitnesse_result', parent.document.body).height($(document.body).height() + 50); }
  $(function() { resize(); });
  $(document).on("click", "article tr.scenario td, article tr.exception td, article .expandall, article .collapseall, article .collapsible", resize );

</script>

</body>
</html>

fitnesse/templates/fitnesse/job_settings.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Настройки для {{ Job.name }}</title>
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'app/favicon.ico' %}" />
</head>
<body>
  <form action="{% url 'fitnesse:job_settings_save' Job.id %}" method="post" role="form">
    {% csrf_token %}
    <div class="container">
      <div class="page-header">
        <h1>Настройки для {{ Job.name }}</h1>
      </div>
      <div class="form-group">
        <label for="MaxBuilds-id">Максимальное кол-во хранимых билдов</label>
        <input class="form-control" type="number" name="MaxBuilds" id="MaxBuilds-id" value="{{ MaxBuilds }}" placeholder="50">
      </div>
      <button type="submit" class="btn btn-default">Сохранить</button>
    </div>
  </form>
  <script src="{% static 'jquery/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

fitnesse/templates/fitnesse/jobs.html
{% extends "fitnesse/_base.html" %}
{% load staticfiles %}
{% block title %}Результаты fitnesse тестов{% endblock %}
{% block body %}
<div class="container">
  <div class="page-header">
    <h1>Результаты fitnesse тестов</h1>
  </div>
  <div class="panel panel-default">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header"><p class="navbar-text">Список задач</p></div>
        <div class="collapse navbar-collapse navbar-right">
            <button type="button" onclick="document.location = '{% url 'fitnesse:common_settings_show' %}'" class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-wrench"></span> Settings</button>
            <button type="button" onclick="document.location = '{% url 'fitnesse:changelog' %}'" class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-bullhorn"></span> Changelog</button>
        </div>
      </div>
    </nav>
    <div class="panel-body">
      <ul class="nav nav-pills nav-stacked">
      {% for rec in jobs %}
        <li>
          <ul class="nav nav-pills">
            <li class="nav-job">
              <a href="{% url 'fitnesse:results_aggregation' rec.id %}" class="navbar-link">{{ rec.name }}
                <div class="pull-right">
                  <span class="badge col-build-count">{{ rec.build_count }}</span>
                  <span class="col-build-last-stat">{{ rec.last_build_stat }}</span>
                  <span class="col-build-last-time">{{ rec.start_time }}</span>
                  <span class="col-build-last">{{ rec.build_last }}</span>
                </div>
              </a>
            </li>
            <li class="dropdown pull-right">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'fitnesse:job_settings_show' rec.id %}" class="navbar-link"><span class="glyphicon glyphicon-wrench"></span> Settings</a></li>
                <li><a href="{% url 'fitnesse:job_charts' rec.id %}" class="navbar-link"><span class="glyphicon glyphicon-signal"></span> Charts</a></li>
              </ul>
            </li>
          </ul>
        </li>
      {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

fitnesse/templates/fitnesse/test_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Результаты fitnesse теста</title>
  <link rel="stylesheet" type="text/css" href="{% static 'fitnesse/project/css/fitnesse.css' %}" />
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'app/favicon.ico' %}" />
  <style type="text/css">
  #frame_fitnesse_result {
    top:0px;
    left:0px;
    width:100%;   
  }

  .test-content {
    margin-left: 50px;
    margin-right: 50px;
  }

  #clientw8 {
    overflow: auto;
    font-family: "Fixedsys";
    font-size: 12px;
  }

  .main_log {
    padding: 15px;
    border: 1px solid transparent;
    border-radius: 6px;
    background-color: #e5e5e5;
  }

  .fitnesse-error {
    color: red;
    display: inline-block;
  }
</style>
</head>
  <body>
    <ol class="fit_breadcrumb">
      <li><a href="/fitnesse/">Home</a><span class="divider">/</span></li>
      <li><a href="/fitnesse/{{job.id}}/">{{job.name}}</a><span class="divider">/</span></li>
      <li class="active">{{test_name}}</li>
      <li><span> (build: </span><a href="{{build_url}}/" target="_blank">{{build_id}}</a><span>)</span></li>
    </ol>
    <div class="test-content">

      <ul class="nav nav-tabs" id="myTab" data-tabs="tabs">
        <li class="active">
          <a href="#fitnesse_result" data-toggle="tab">Fitnesse result</a>
        </li>
        <li>
          <a href="#clientw8" data-toggle="tab">ClientW8</a>
        </li>
      </ul>
      <div id="content" class="tab-content">
        <div class="tab-pane active" id="fitnesse_result">
          <iframe id="frame_fitnesse_result" src="{% url 'fitnesse:fitnesse_result' job.id test_id %}" frameborder="no" seamless scrolling="no">
            Браузер не поддерживает iframe. Обновитесь.
          </iframe>
        </div>  
        <div class="tab-pane" id="clientw8">
          {% autoescape off %}
          {{ fitnesse_result.before }}
          <div class="main_log">{{ fitnesse_result.test }}</div>
          {{ fitnesse_result.after }}
          {% endautoescape %}
        </div>
      </div>

    </div>

    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>